package view;

import controller.FormCadastroProfessorController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;


public class FormCadastroProfessorView extends javax.swing.JFrame {

    private final FormCadastroProfessorController controller;
    /**
     * Creates new form FormPesquisaProfessorView
     */
    public FormCadastroProfessorView() {
        initComponents();
        controller = new FormCadastroProfessorController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNomeNovoProfessor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoHorasTrabalhadasNovoProfessor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoTelefoneNovoProfessor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoCPFNovoProfessor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoEnderecoNovoProfessor = new javax.swing.JTextField();
        botaoSalvarTelaCadastroProfessor = new javax.swing.JButton();
        campoSalarioNovoProfessor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Salário (apenas números)");

        jLabel3.setText("Horas de Trabalho");

        jLabel4.setText("Telefone");

        jLabel5.setText("CPF");

        jLabel6.setText("Endereço");

        botaoSalvarTelaCadastroProfessor.setText("Salvar");
        botaoSalvarTelaCadastroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarTelaCadastroProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(campoNomeNovoProfessor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(campoTelefoneNovoProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(campoSalarioNovoProfessor))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoHorasTrabalhadasNovoProfessor)
                                    .addComponent(campoCPFNovoProfessor)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addGap(0, 59, Short.MAX_VALUE))))
                            .addComponent(campoEnderecoNovoProfessor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(botaoSalvarTelaCadastroProfessor)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeNovoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoHorasTrabalhadasNovoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSalarioNovoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefoneNovoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCPFNovoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEnderecoNovoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(botaoSalvarTelaCadastroProfessor)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarTelaCadastroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarTelaCadastroProfessorActionPerformed
        try {
            controller.salvaNovoProfessor();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FormCadastroProfessorView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoSalvarTelaCadastroProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroProfessorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvarTelaCadastroProfessor;
    private javax.swing.JTextField campoCPFNovoProfessor;
    private javax.swing.JTextField campoEnderecoNovoProfessor;
    private javax.swing.JTextField campoHorasTrabalhadasNovoProfessor;
    private javax.swing.JTextField campoNomeNovoProfessor;
    private javax.swing.JTextField campoSalarioNovoProfessor;
    private javax.swing.JTextField campoTelefoneNovoProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    public JTextField getCampoCPFNovoProfessor() {
        return campoCPFNovoProfessor;
    }

    public void setCampoCPFNovoProfessor(JTextField campoCPFNovoProfessor) {
        this.campoCPFNovoProfessor = campoCPFNovoProfessor;
    }

    public JTextField getCampoEnderecoNovoProfessor() {
        return campoEnderecoNovoProfessor;
    }

    public void setCampoEnderecoNovoProfessor(JTextField campoEnderecoNovoProfessor) {
        this.campoEnderecoNovoProfessor = campoEnderecoNovoProfessor;
    }

    public JTextField getCampoHorasTrabalhadasNovoProfessor() {
        return campoHorasTrabalhadasNovoProfessor;
    }

    public void setCampoHorasTrabalhadasNovoProfessor(JTextField campoHorasTrabalhadasNovoProfessor) {
        this.campoHorasTrabalhadasNovoProfessor = campoHorasTrabalhadasNovoProfessor;
    }

    public JTextField getCampoNomeNovoProfessor() {
        return campoNomeNovoProfessor;
    }

    public void setCampoNomeNovoProfessor(JTextField campoNomeNovoProfessor) {
        this.campoNomeNovoProfessor = campoNomeNovoProfessor;
    }

    public JTextField getCampoSalarioNovoProfessor() {
        return campoSalarioNovoProfessor;
    }

    public void setCampoSalarioNovoProfessor(JTextField campoSalarioNovoProfessor) {
        this.campoSalarioNovoProfessor = campoSalarioNovoProfessor;
    }

    public JTextField getCampoTelefoneNovoProfessor() {
        return campoTelefoneNovoProfessor;
    }

    public void setCampoTelefoneNovoProfessor(JTextField campoTelefoneNovoProfessor) {
        this.campoTelefoneNovoProfessor = campoTelefoneNovoProfessor;
    }


    
}
